In [17]:
import pandas as pd
import os

# --- Configuration ---
# Set the filename. This must match the file you just downloaded.
FILE_NAME = "Reviews.csv"
DATA_FILE_PATH = os.path.join(os.getcwd(), FILE_NAME)

# How many rows to load for initial testing?
# 25000 is a good sample.
NUM_ROWS_TO_LOAD = 25000

# --- Load Data ---
print(f"Attempting to load the first {NUM_ROWS_TO_LOAD} rows from local file: {DATA_FILE_PATH}...")

try:
    # Use Pandas to read the local CSV file
    # We use 'nrows' to only load the first 5000 for a quick test
    df = pd.read_csv(DATA_FILE_PATH, nrows=NUM_ROWS_TO_LOAD)

    print(f"\nSuccessfully loaded {len(df)} rows.")
    
    # Display the first few rows and column names
    print("\n--- First 5 rows: ---")
    print(df.head())
    
    print("\n--- Columns available: ---")
    print(df.columns)
    
    # Check for missing values in the key columns we need
    print("\n--- Missing values check: ---")
    # 'ProductId' is for searching, 'Text' is our context
    key_columns = ['ProductId', 'Text'] 
    print(df[key_columns].isnull().sum())
    
    print("\n--- Example Review Body ('Text' column): ---")
    first_valid_review = df['Text'].dropna().iloc[0]
    print(first_valid_review)

except FileNotFoundError:
    print(f"\n*** ERROR: File not found! ***")
    print(f"Please make sure the file '{FILE_NAME}' is in the same directory as your notebook:")
    print(f"{os.getcwd()}")
except Exception as e:
    print(f"\nAn error occurred: {e}")

Attempting to load the first 25000 rows from local file: d:\Karunya\4th Year\Generative_AI\3rd_IA\Reviews.csv...

Successfully loaded 25000 rows.

--- First 5 rows: ---
   Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400
1                     0                       0      1  1346976000
2                     1                       1      4  1219017600
3                     3                       3      2  1307923200
4                     0                       0      5  1350777600

                 Summary                                               Text
0  Good Quality Dog Food  I have bought several of the Vitality canned d...
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...
2  "Delight" says it all  This is a confection that has been around a fe...
3         Cough Medicine  If you are looking for the secret ingredient i...
4            Great taffy  Great taffy at a great price.  There was a wid...

--- Columns available: ---
Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

--- Missing values check: ---
ProductId    0
Text         0
dtype: int64

--- Example Review Body ('Text' column): ---
I have bought several of the Vitality canned dog food products and have found them all to be of good quality. The product looks more like a stew than a processed meat and it smells better. My Labrador is finicky and she appreciates this product better than  most.

In [2]:
# %pip install tqdm

In [3]:
# %pip install protobuf

In [4]:
import torch

if torch.cuda.is_available():
    print("✅ GPU is available and PyTorch can see it!")
    print(f"Device Name: {torch.cuda.get_device_name(0)}")
    device_to_use = 0 # Use the first GPU
else:
    print("⚠️ GPU not found by PyTorch. Using CPU instead.")
    print("   If you have an NVIDIA GPU, make sure CUDA drivers are installed correctly.")
    print("   and that you installed the CUDA-enabled version of PyTorch.")
    device_to_use = -1 # Use CPU

# This variable will be used by the pipeline later
# (Just ensuring it's set globally in the notebook)
%store device_to_use

✅ GPU is available and PyTorch can see it!
Device Name: NVIDIA GeForce RTX 4050 Laptop GPU
Stored 'device_to_use' (int)

In [5]:
# from huggingface_hub import snapshot_download
# import os

# # Create a main directory to store all local models
# models_dir = "./models"
# os.makedirs(models_dir, exist_ok=True)

# # --- Model 1: Question Generation (QG) ---
# model_name_qg = "valhalla/t5-small-qg-hl"
# local_dir_qg = os.path.join(models_dir, "qg_model")

# print(f"Downloading QG model '{model_name_qg}' to '{local_dir_qg}'...")
# snapshot_download(
#     repo_id=model_name_qg,
#     local_dir=local_dir_qg,
#     local_dir_use_symlinks=False  # Important for Windows
# )
# print("QG model download complete.")


# # --- Model 2: Question Answering (QA) ---
# model_name_qa = "distilbert-base-cased-distilled-squad"
# local_dir_qa = os.path.join(models_dir, "qa_model")

# print(f"\nDownloading QA model '{model_name_qa}' to '{local_dir_qa}'...")
# snapshot_download(
#     repo_id=model_name_qa,
#     local_dir=local_dir_qa,
#     local_dir_use_symlinks=False  # Important for Windows
# )
# print("QA model download complete.")

In [ ]:
# import pandas as pd
# from transformers import pipeline, T5Tokenizer  # <-- Import T5Tokenizer directly
# from tqdm import tqdm
# import torch
# import os

# # --- Configuration ---
# ROWS_TO_PROCESS = 25
# LOCAL_QG_MODEL_PATH = os.path.join("./models", "qg_model")
# LOCAL_QA_MODEL_PATH = os.path.join("./models", "qa_model")

# # --- Get Data and Device ---
# %store -r device_to_use
# print(f"Using device: {'GPU (cuda:0)' if device_to_use == 0 else 'CPU'}")

# if 'df' in locals() and len(df) >= ROWS_TO_PROCESS:
#     sample_df = df.head(ROWS_TO_PROCESS).copy()
#     print(f"Starting Q&A generation with a sample of {len(sample_df)} reviews.")
# else:
#     print("Error: 'df' not found. Please re-run the cell that loads 'Reviews.csv'.")
#     raise NameError("'df' DataFrame not found.")

# # --- Setup Models (Loading with *Explicit* T5Tokenizer) ---
# try:
#     print(f"\nLoading QG tokenizer from local path: {LOCAL_QG_MODEL_PATH}...")
#     # *** FIX: Use T5Tokenizer directly ***
#     qg_tokenizer = T5Tokenizer.from_pretrained(LOCAL_QG_MODEL_PATH)
#     print("QG tokenizer loaded.")

#     print(f"\nLoading QG model from local path: {LOCAL_QG_MODEL_PATH}...")
#     qg_pipeline = pipeline(
#         "text2text-generation",
#         model=LOCAL_QG_MODEL_PATH,
#         tokenizer=qg_tokenizer,  # <-- Pass the T5Tokenizer
#         device=device_to_use
#     )
#     print("QG model loaded.")

#     print(f"\nLoading QA model from local path: {LOCAL_QA_MODEL_PATH}...")
#     qa_pipeline = pipeline(
#         "question-answering",
#         model=LOCAL_QA_MODEL_PATH,
#         device=device_to_use
#     )
#     print("QA model loaded.")

#     # --- Q&A Generation Function (Same as before) ---
#     def generate_qa_pair(row_text):
#         context = row_text
#         if not isinstance(context, str) or len(context.split()) < 20:
#             return None, None
#         try:
#             truncated_context = context[:1500]
#             generated_output = qg_pipeline(truncated_context, max_length=64, num_beams=4, early_stopping=True)
#             if not generated_output: return None, None 
#             question = generated_output[0]['generated_text']

#             if not question or '?' not in question: return None, None

#             answer_dict = qa_pipeline(question=question, context=context)
#             if not answer_dict: return None, None

#             answer = answer_dict.get('answer', None)
#             score = answer_dict.get('score', 0) 

#             if answer is None or score < 0.3 or len(answer.split()) < 2:
#                 return None, None
#             return question, answer
#         except Exception:
#              return None, None

#     # --- Run the Process ---
#     if not sample_df.empty:
#         print(f"\n🚀 Generating Q&A pairs for {len(sample_df)} reviews... (Using {'GPU' if device_to_use == 0 else 'CPU'})")
#         tqdm.pandas(desc="Processing Reviews")
#         results = sample_df['Text'].progress_apply(generate_qa_pair)
#         sample_df[['generated_question', 'generated_answer']] = pd.DataFrame(results.tolist(), index=sample_df.index)

#         print("\n✅ Generation complete.")
        
#         # --- Show Results ---
#         final_qa_data = sample_df.dropna(subset=['generated_question', 'generated_answer']).copy()
#         print(f"Successfully created {len(final_qa_data)} valid Q&A pairs.")
#         print("\n--- Generated Q&A Dataset (Sample): ---")
#         print(final_qa_data[['Text', 'generated_question', 'generated_answer']].head())

# except Exception as e:
#     print(f"\n❌ An error occurred: {e}")

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

Using device: GPU (cuda:0)
Starting Q&A generation with a sample of 25 reviews.

Loading QG tokenizer from local path: ./models\qg_model...
QG tokenizer loaded.

Loading QG model from local path: ./models\qg_model...

Device set to use cuda:0

QG model loaded.

Loading QA model from local path: ./models\qa_model...

Device set to use cuda:0

QA model loaded.

🚀 Generating Q&A pairs for 25 reviews... (Using GPU)

Processing Reviews:   0%|          | 0/25 [00:00<?, ?it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:   8%|▊         | 2/25 [00:00<00:09,  2.50it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  12%|█▏        | 3/25 [00:00<00:06,  3.26it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  16%|█▌        | 4/25 [00:01<00:06,  3.47it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  20%|██        | 5/25 [00:01<00:04,  4.27it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  24%|██▍       | 6/25 [00:01<00:03,  4.83it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  28%|██▊       | 7/25 [00:01<00:03,  4.93it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  32%|███▏      | 8/25 [00:01<00:03,  5.29it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  36%|███▌      | 9/25 [00:02<00:02,  5.54it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  40%|████      | 10/25 [00:02<00:02,  5.60it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  44%|████▍     | 11/25 [00:02<00:02,  5.95it/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  48%|████▊     | 12/25 [00:02<00:02,  5.79it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  52%|█████▏    | 13/25 [00:02<00:02,  5.71it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  56%|█████▌    | 14/25 [00:02<00:02,  5.27it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  64%|██████▍   | 16/25 [00:03<00:01,  7.27it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  68%|██████▊   | 17/25 [00:03<00:01,  7.00it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  72%|███████▏  | 18/25 [00:03<00:01,  5.82it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  76%|███████▌  | 19/25 [00:03<00:01,  5.74it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  80%|████████  | 20/25 [00:03<00:00,  5.66it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  84%|████████▍ | 21/25 [00:04<00:00,  5.85it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  88%|████████▊ | 22/25 [00:04<00:00,  5.62it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  92%|█████████▏| 23/25 [00:04<00:00,  5.73it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews:  96%|█████████▌| 24/25 [00:04<00:00,  5.42it/s]Both `max_new_tokens` (=256) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Processing Reviews: 100%|██████████| 25/25 [00:04<00:00,  5.21it/s]

✅ Generation complete.
Successfully created 12 valid Q&A pairs.

--- Generated Q&A Dataset (Sample): ---
                                                Text  \
1  Product arrived labeled as Jumbo Salted Peanut...
2  This is a confection that has been around a fe...
3  If you are looking for the secret ingredient i...
5  I got a wild hair for taffy and ordered this f...
6  This saltwater taffy had great flavors and was...

                                  generated_question  \
1         What was the name of Jumbo Salted Peanuts?
2  What is the name of the treat that seduces Edm...
3                     What ingredient is Robitussin?
5  What was the name of the bag I ordered for taffy?
6        What was the flavor of the saltwater taffy?

                        generated_answer
1                   Jumbo Salted Peanuts
2  The Lion, The Witch, and The Wardrobe
3                      secret ingredient
5                         five pound bag
6                    very soft and chewy

## Q&A pairs

In [18]:
import pandas as pd
from transformers import pipeline, T5Tokenizer
from tqdm import tqdm
import torch
import os

# --- Configuration ---
# Let's process all 25000 rows we loaded in 'df'
ROWS_TO_PROCESS = 25000 
LOCAL_QG_MODEL_PATH = os.path.join("./models", "qg_model")
LOCAL_QA_MODEL_PATH = os.path.join("./models", "qa_model")
OUTPUT_FILE = "generated_qa_dataset.csv"

# --- Get Data and Device ---
%store -r device_to_use
print(f"Using device: {'GPU (cuda:0)' if device_to_use == 0 else 'CPU'}")

if 'df' in locals() and len(df) >= ROWS_TO_PROCESS:
    # Use the full 25000-row sample this time
    sample_df = df.head(ROWS_TO_PROCESS).copy()
    print(f"Starting Q&A generation for {len(sample_df)} reviews.")
else:
    print(f"Error: 'df' not found or is smaller than {ROWS_TO_PROCESS} rows.")
    print("Please re-run the cell that loads 'Reviews.csv' and ensure 'nrows' is at least 25000.")
    raise NameError("'df' DataFrame not found or has too few rows.")

# --- Setup Models (Loading from Local Disk) ---
try:
    print(f"\nLoading QG tokenizer from local path: {LOCAL_QG_MODEL_PATH}...")
    qg_tokenizer = T5Tokenizer.from_pretrained(LOCAL_QG_MODEL_PATH)
    print("QG tokenizer loaded.")

    print(f"\nLoading QG model from local path: {LOCAL_QG_MODEL_PATH}...")
    qg_pipeline = pipeline(
        "text2text-generation",
        model=LOCAL_QG_MODEL_PATH,
        tokenizer=qg_tokenizer,
        device=device_to_use
    )
    print("QG model loaded.")

    print(f"\nLoading QA model from local path: {LOCAL_QA_MODEL_PATH}...")
    qa_pipeline = pipeline(
        "question-answering",
        model=LOCAL_QA_MODEL_PATH,
        device=device_to_use
    )
    print("QA model loaded.")

    # --- Q&A Generation Function (with fix) ---
    def generate_qa_pair(row_text):
        context = row_text
        if not isinstance(context, str) or len(context.split()) < 20:
            return None, None
        try:
            truncated_context = context[:1500]
            
            # *** FIX: Use max_new_tokens instead of max_length ***
            generated_output = qg_pipeline(
                truncated_context, 
                max_new_tokens=64,  # <-- This is the fix
                num_beams=4, 
                early_stopping=True
            )
            
            if not generated_output: return None, None 
            question = generated_output[0]['generated_text']

            if not question or '?' not in question: return None, None

            answer_dict = qa_pipeline(question=question, context=context)
            if not answer_dict: return None, None

            answer = answer_dict.get('answer', None)
            score = answer_dict.get('score', 0) 

            if answer is None or score < 0.3 or len(answer.split()) < 2:
                return None, None
            return question, answer
        except Exception:
             return None, None

    # --- Run the Process ---
    if not sample_df.empty:
        print(f"\n🚀 Generating Q&A pairs for {len(sample_df)} reviews...")
        print("This will take a significant amount of time (e.g., 20-40 minutes).")
        print("This is a good time to take a break!")
        
        tqdm.pandas(desc="Processing Reviews")
        results = sample_df['Text'].progress_apply(generate_qa_pair)
        sample_df[['generated_question', 'generated_answer']] = pd.DataFrame(results.tolist(), index=sample_df.index)

        print("\n✅ Generation complete.")
        
        # --- Save Results ---
        final_qa_data = sample_df.dropna(subset=['generated_question', 'generated_answer']).copy()
        
        # We need the context, question, and answer for training
        # Let's rename 'Text' to 'context' for clarity in the next phase
        final_qa_data.rename(columns={'Text': 'context'}, inplace=True)
        
        # Select only the columns we need for training
        training_df = final_qa_data[['context', 'generated_question', 'generated_answer']]
        
        # Save to a new CSV file
        training_df.to_csv(OUTPUT_FILE, index=False)
        
        print(f"\nSuccessfully created and saved {len(training_df)} valid Q&A pairs to '{OUTPUT_FILE}'.")
        print("\n--- Final Dataset (Sample): ---")
        print(training_df.head())


except Exception as e:
    print(f"\n❌ An error occurred: {e}")

Using device: GPU (cuda:0)
Starting Q&A generation for 25000 reviews.

Loading QG tokenizer from local path: ./models\qg_model...
QG tokenizer loaded.

Loading QG model from local path: ./models\qg_model...

Device set to use cuda:0

QG model loaded.

Loading QA model from local path: ./models\qa_model...

Device set to use cuda:0

QA model loaded.

🚀 Generating Q&A pairs for 25000 reviews...
This will take a significant amount of time (e.g., 20-40 minutes).
This is a good time to take a break!

Processing Reviews:   3%|▎         | 746/25000 [02:15<1:03:32,  6.36it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (632 > 512). Running this sequence through the model will result in indexing errors
Processing Reviews: 100%|██████████| 25000/25000 [1:45:35<00:00,  3.95it/s]

✅ Generation complete.

Successfully created and saved 7058 valid Q&A pairs to 'generated_qa_dataset.csv'.

--- Final Dataset (Sample): ---
                                             context  \
1  Product arrived labeled as Jumbo Salted Peanut...
2  This is a confection that has been around a fe...
3  If you are looking for the secret ingredient i...
5  I got a wild hair for taffy and ordered this f...
6  This saltwater taffy had great flavors and was...

                                  generated_question  \
1         What was the name of Jumbo Salted Peanuts?
2  What is the name of the treat that seduces Edm...
3                     What ingredient is Robitussin?
5  What was the name of the bag I ordered for taffy?
6        What was the flavor of the saltwater taffy?

                        generated_answer
1                   Jumbo Salted Peanuts
2  The Lion, The Witch, and The Wardrobe
3                      secret ingredient
5                         five pound bag
6                    very soft and chewy

## Splitting Data

In [19]:
from datasets import load_dataset, DatasetDict

# --- Configuration ---
DATASET_FILE = "generated_qa_dataset.csv"

# --- Load Data ---
print(f"Loading our generated dataset from {DATASET_FILE}...")
try:
    # Load the CSV file as a Hugging Face Dataset object
    full_dataset = load_dataset('csv', data_files=DATASET_FILE, split='train')
    
    # --- Split Data ---
    # We need to find the answer_start index for our text-based answer
    # This is a bit of a workaround to add the 'answer_start' column
    def find_answer_start(example):
        # We'll store the answer as a dictionary, just like the SQuAD dataset
        answer_text = example['generated_answer']
        context_text = example['context']
        
        answer_start = context_text.find(answer_text)
        
        # If the answer isn't found (shouldn't happen, but good to check)
        if answer_start == -1:
            return {'answers': {'text': [], 'answer_start': []}}
        
        return {
            'answers': {
                'text': [answer_text],
                'answer_start': [answer_start]
            }
        }

    print("Formatting answers to SQuAD format...")
    full_dataset = full_dataset.map(find_answer_start, remove_columns=['generated_answer'])
    
    # Now, split the dataset into training (90%) and testing (10%)
    # Using shuffle=True is good practice
    train_test_split = full_dataset.train_test_split(test_size=0.1, shuffle=True, seed=42)
    
    # Rename for clarity
    datasets = DatasetDict({
        'train': train_test_split['train'],
        'test': train_test_split['test']
    })

    print("\n✅ Dataset loaded and split successfully.")
    print(datasets)
    
    print("\n--- Example Training Data: ---")
    print(datasets['train'][0])

except FileNotFoundError:
    print(f"\n*** ERROR: File not found! ***")
    print(f"Could not find '{DATASET_FILE}'. Please make sure it's in the same directory.")
except Exception as e:
    print(f"\nAn error occurred: {e}")

Loading our generated dataset from generated_qa_dataset.csv...

Generating train split: 0 examples [00:00, ? examples/s]

Formatting answers to SQuAD format...

Map:   0%|          | 0/7058 [00:00<?, ? examples/s]

✅ Dataset loaded and split successfully.
DatasetDict({
    train: Dataset({
        features: ['context', 'generated_question', 'answers'],
        num_rows: 6352
    })
    test: Dataset({
        features: ['context', 'generated_question', 'answers'],
        num_rows: 706
    })
})

--- Example Training Data: ---
{'context': 'Instead of just being pork rinds, oil, salt and vinegar, they have lactose and maltodextrin on them, contributing to 2g of sugar per serving.  Many people (myself included) who buy this kind of snack who are on low carbohydrate diets; they will not be happy about the sugar.<br /><br />The labeling on the package is very strange, and I am surprised it gets by the nice government men who worry about this sort of thing.  It says Total Carbohydrates are less then 1g, so they get to put zero grams.  Ok, fair enough, I have seen that before.  But then the label admits to 2 grams of sugar, which is a carbohydrate.  How they can get away with saying they have zero grams of carbs when there are 2 grams of sugar is beyond me.  I assume it is just that nobody has caught them yet.<br /><br />Then there is protein.  The nutritional analysis says 8g of protein per serving.  Not bad for a snack food.  Right next to the 8g is says "Not a significant source of protein."  Huh...A slice of cheese is about 8 grams of protein, as is an ounce of meet.  I believe those are significant sources of protein.<br /><br />I went to their website, to check out the nutritional facts.  I did notice they were high in sodium.  What I missed was that they claim the number of servings in a 1.75 oz package was three (3), so the sodium in a package is actually three times higher.  I doubt many people expect a 1.75 oz package to be three servings.  I just looked up Fritos Corn chips.  A 2 oz package is considered a single serving package, and the analysis on the back shows one serving.  So when Fritos tells you the sodium level, it is only 320 mg for the entire package.  For these pork rinds, the 1.75 oz package is 900 mg of sodium, about half of your daily requirement.  A little steep for a snack.<br /><br />Although I went to their site to look at some nutritional info, they don\'t shows the label or the actual ingredients on their site or at Amazon.  If they had, I would not have purchased it.  They use partially hydrogenated oil, a kind of fat may be destructive to your health long term.  Since the government broke down and required that partially hydrogenated oil be listed on the label, a lot of the food industry has switched away from it, as people are correctly suspicious of it.<br /><br />To add insult to injury, I was unhappy with the taste.  They have a chemical, nasty taste.  I suppose that is subjective, but a few bites left me a little queasy.<br /><br />I feel bad having bought this, but perhaps my error will be of some use to others looking for a low carb snack.  Please pass this company\'s products by, and let\'s find someone else who can actually provide us the food we want and the information we need in a rational, ethical and legal way.', 'generated_question': 'What does the label say is not a significant source of protein?', 'answers': {'answer_start': [975], 'text': ['A slice of cheese']}}

## Set Up Model, Tokenizer, and Preprocessing

In [20]:
from transformers import AutoTokenizer, AutoModelForQuestionAnswering, TrainingArguments, Trainer, DefaultDataCollator
import os

# --- Configuration ---
# Use the local QA model we downloaded as our base for fine-tuning
MODEL_CHECKPOINT = os.path.join("./models", "qa_model")
# This is where we will save our *new* fine-tuned model
NEW_MODEL_DIR = os.path.join("./models", "my_final_qa_model")

# Tokenizer settings
MAX_LENGTH = 384 # Max length of a question + context chunk
DOC_STRIDE = 128 # Overlap between chunks if context is too long

# --- Load Tokenizer ---
print(f"Loading tokenizer from local path: {MODEL_CHECKPOINT}")
# We use 'use_fast=True' as it's required for the offset mappings
tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT, use_fast=True)
print("Tokenizer loaded.")

# --- Preprocessing Function ---
# This is the most complex step. It formats the data for the model.
def preprocess_function(examples):
    # Tokenize questions and contexts together
    # Truncation="only_second" means we only truncate the context, not the question
    tokenized_examples = tokenizer(
        examples["generated_question"],
        examples["context"],
        truncation="only_second",
        max_length=MAX_LENGTH,
        stride=DOC_STRIDE,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    # offset_mapping gives us a map from token-level to character-level in the original text
    offset_mapping = tokenized_examples.pop("offset_mapping")
    
    # sample_mapping maps from a new feature (a chunk) back to its original example
    sample_mapping = tokenized_examples.pop("overflow_to_sample_mapping")

    # These will be our new labels
    tokenized_examples["start_positions"] = []
    tokenized_examples["end_positions"] = []

    for i, offsets in enumerate(offset_mapping):
        # Get the ID of the original example
        sample_index = sample_mapping[i]
        answers = examples["answers"][sample_index]
        
        # If there's no answer for this example, label (0, 0)
        if len(answers["answer_start"]) == 0:
            tokenized_examples["start_positions"].append(0)
            tokenized_examples["end_positions"].append(0)
            continue

        # Get the start and end character positions of the answer
        start_char = answers["answer_start"][0]
        end_char = start_char + len(answers["text"][0])

        # Get the token indices that correspond to the current feature (chunk)
        sequence_ids = tokenized_examples.sequence_ids(i)

        # Find the start and end of the context part in the tokenized input
        idx = 0
        while sequence_ids[idx] != 1: # sequence_id 1 is the context
            idx += 1
        context_start = idx
        while sequence_ids[idx] == 1:
            idx += 1
        context_end = idx - 1

        # Check if the answer is completely outside the current chunk
        if (offsets[context_start][0] > end_char or offsets[context_end][1] < start_char):
            tokenized_examples["start_positions"].append(0)
            tokenized_examples["end_positions"].append(0)
        else:
            # Find the token start index
            token_start_index = context_start
            while token_start_index <= context_end and offsets[token_start_index][0] < start_char:
                token_start_index += 1
            
            # Find the token end index
            token_end_index = context_end
            while token_end_index >= context_start and offsets[token_end_index][1] > end_char:
                token_end_index -= 1

            tokenized_examples["start_positions"].append(token_start_index)
            tokenized_examples["end_positions"].append(token_end_index)

    return tokenized_examples

# --- Apply Preprocessing ---
if 'datasets' in locals():
    print("\nApplying preprocessing to the dataset... (This may take a moment)")
    # Use .map() to apply the function to all examples
    # batched=True processes multiple examples at once
    tokenized_datasets = datasets.map(
        preprocess_function,
        batched=True,
        remove_columns=datasets["train"].column_names
    )
    print("Preprocessing complete.")
    print(tokenized_datasets)
else:
    print("Error: 'datasets' not found. Please re-run the previous cell.")

Loading tokenizer from local path: ./models\qa_model
Tokenizer loaded.

Applying preprocessing to the dataset... (This may take a moment)

Map:   0%|          | 0/6352 [00:00<?, ? examples/s]

Map:   0%|          | 0/706 [00:00<?, ? examples/s]

Preprocessing complete.
DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'start_positions', 'end_positions'],
        num_rows: 6836
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'start_positions', 'end_positions'],
        num_rows: 753
    })
})

## Fine-Tuning Model!

In [21]:
import torch
from transformers import AutoModelForQuestionAnswering, TrainingArguments, Trainer, DefaultDataCollator
import os

# --- Configuration ---
MODEL_CHECKPOINT = os.path.join("./models", "qa_model")
NEW_MODEL_DIR = os.path.join("./models", "my_final_qa_model")

# --- Load Model ---
print(f"Loading pre-trained model from local path: {MODEL_CHECKPOINT}")
model = AutoModelForQuestionAnswering.from_pretrained(MODEL_CHECKPOINT)
print("Model loaded.")

# --- Set Training Arguments ---
# These arguments control the fine-tuning process
training_args = TrainingArguments(
    output_dir=NEW_MODEL_DIR,
    # --- FIX ---
    logging_strategy="epoch",  # Log at the same time as evaluation
    # ---
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    push_to_hub=False,
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none",
)

# Data collator handles batching our examples together
data_collator = DefaultDataCollator()

# --- Initialize Trainer ---
print("Initializing Trainer...")
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)
print("Trainer initialized.")

# --- START FINE-TUNING ---
if 'trainer' in locals():
    print("\n🚀 *** STARTING FINE-TUNING! *** 🚀")
    print("This will run for several minutes. You'll see the loss go down.")
    
    try:
        # This is the command that starts the training
        trainer.train()
        
        print("\n✅ *** FINE-TUNING COMPLETE! *** ✅")
        
        # --- Save the Final Model ---
        print(f"Saving the best model to {NEW_MODEL_DIR}...")
        trainer.save_model()
        print("Model saved successfully.")
        
    except torch.cuda.OutOfMemoryError:
        print("\n❌ *** CUDA Out of Memory! *** ❌")
        print("Your GPU ran out of memory. Try this:")
        print("1. Restart the kernel.")
        print("2. In the 'TrainingArguments' cell, change 'per_device_train_batch_size=16' to 'per_device_train_batch_size=8'.")
        print("3. Re-run this cell.")
    except Exception as e:
        print(f"\nAn error occurred during training: {e}")
else:
    print("Error: 'trainer' not initialized. Please re-run the previous cells.")

Loading pre-trained model from local path: ./models\qa_model
Model loaded.
Initializing Trainer...

C:\Users\jimma\AppData\Local\Temp\ipykernel_12324\438245872.py:38: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Trainer initialized.

🚀 *** STARTING FINE-TUNING! *** 🚀
This will run for several minutes. You'll see the loss go down.

✅ *** FINE-TUNING COMPLETE! *** ✅
Saving the best model to ./models\my_final_qa_model...
Model saved successfully.

In [22]:
from huggingface_hub import snapshot_download
import os

# Create a main directory to store all local models
models_dir = "./models"
os.makedirs(models_dir, exist_ok=True)

# --- Model 3: T5-Small (Summarization/Generative) ---
model_name_t5 = "t5-small"
local_dir_t5 = os.path.join(models_dir, "t5_small")

print(f"Downloading T5-Small model '{model_name_t5}' to '{local_dir_t5}'...")
snapshot_download(
    repo_id=model_name_t5,
    local_dir=local_dir_t5,
    local_dir_use_symlinks=False  # Important for Windows
)
print("T5-Small model download complete.")

Downloading T5-Small model 't5-small' to './models\t5_small'...

c:\Users\jimma\anaconda3\envs\productqa-env\lib\site-packages\huggingface_hub\file_download.py:979: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(

Fetching 20 files:   0%|          | 0/20 [00:00<?, ?it/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

.gitattributes:   0%|          | 0.00/537 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/8.47k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

decoder_model_merged_quantized.onnx:   0%|          | 0.00/58.7M [00:00<?, ?B/s]

decoder_model.onnx:   0%|          | 0.00/232M [00:00<?, ?B/s]

decoder_model_merged.onnx:   0%|          | 0.00/233M [00:00<?, ?B/s]

flax_model.msgpack:   0%|          | 0.00/242M [00:00<?, ?B/s]

decoder_model_quantized.onnx:   0%|          | 0.00/58.4M [00:00<?, ?B/s]

decoder_with_past_model.onnx:   0%|          | 0.00/220M [00:00<?, ?B/s]

decoder_with_past_model_quantized.onnx:   0%|          | 0.00/55.2M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

encoder_model.onnx:   0%|          | 0.00/141M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

encoder_model_quantized.onnx:   0%|          | 0.00/35.5M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

pytorch_model.bin:   0%|          | 0.00/242M [00:00<?, ?B/s]

rust_model.ot:   0%|          | 0.00/242M [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

tf_model.h5:   0%|          | 0.00/242M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

T5-Small model download complete.

In [23]:
from datasets import load_dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, TrainingArguments, Trainer, DataCollatorForSeq2Seq
import os

# --- 1. Configuration ---
DATASET_FILE = "generated_qa_dataset.csv" # The file you already made
MODEL_CHECKPOINT = os.path.join("./models", "t5_small") # The T5 model we just downloaded
NEW_MODEL_DIR = os.path.join("./models", "my_final_T5_qa_model") # The NEW final model

# --- 2. Load and Split Dataset ---
print(f"Loading our generated dataset from {DATASET_FILE}...")
try:
    # Load the CSV file as a Hugging Face Dataset object
    full_dataset = load_dataset('csv', data_files=DATASET_FILE, split='train')
    
    # Split the dataset 90% train, 10% test
    train_test_split = full_dataset.train_test_split(test_size=0.1, shuffle=True, seed=42)
    
    datasets = DatasetDict({
        'train': train_test_split['train'],
        'test': train_test_split['test']
    })
    print("Dataset loaded and split successfully.")
    print(datasets)
except Exception as e:
    print(f"Error loading dataset: {e}")
    raise

# --- 3. Load Tokenizer & Preprocessing ---
print(f"Loading T5 tokenizer from local path: {MODEL_CHECKPOINT}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT)

# We need to format the input for T5
prefix = "question: "
def preprocess_function_t5(examples):
    # Inputs: "question: [QUESTION] context: [CONTEXT]"
    inputs = [
        f"{prefix}{q} context: {c}" 
        for q, c in zip(examples["generated_question"], examples["context"])
    ]
    
    # Outputs: The answer text
    targets = [ans for ans in examples["generated_answer"]]
    
    # Tokenize inputs and targets
    model_inputs = tokenizer(inputs, max_length=512, truncation=True, padding="max_length")
    labels = tokenizer(targets, max_length=128, truncation=True, padding="max_length")

    # Set the tokenized targets as the 'labels'
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

print("Applying T5 preprocessing to the dataset...")
tokenized_datasets = datasets.map(preprocess_function_t5, batched=True)
print("Preprocessing complete.")

# --- 4. Fine-Tuning ---
print(f"Loading T5 model from local path: {MODEL_CHECKPOINT}")
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_CHECKPOINT)

# Use DataCollatorForSeq2Seq for generative models
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

# Set Training Arguments
training_args = TrainingArguments(
    output_dir=NEW_MODEL_DIR,
    eval_strategy="epoch",
    logging_strategy="epoch", # So you can see the training loss
    learning_rate=2e-5,
    per_device_train_batch_size=8, # T5 is bigger, use a smaller batch size
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    push_to_hub=False,
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none",
)

# Initialize Trainer
print("Initializing Trainer...")
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)

print("\n🚀 *** STARTING T5 FINE-TUNING! *** 🚀")
try:
    trainer.train()
    print("\n✅ *** T5 FINE-TUNING COMPLETE! *** ✅")
    print(f"Saving the best model to {NEW_MODEL_DIR}...")
    trainer.save_model()
    print("Model saved successfully.")
except torch.cuda.OutOfMemoryError:
    print("\n❌ *** CUDA Out of Memory! *** ❌")
    print("Your GPU ran out of memory. Try this:")
    print("1. Restart the kernel.")
    print("2. In this cell, change 'per_device_train_batch_size=8' to 'per_device_train_batch_size=4' (and eval to 4).")
    print("3. Re-run this cell.")
except Exception as e:
    print(f"\nAn error occurred during training: {e}")

Loading our generated dataset from generated_qa_dataset.csv...
Dataset loaded and split successfully.
DatasetDict({
    train: Dataset({
        features: ['context', 'generated_question', 'generated_answer'],
        num_rows: 6352
    })
    test: Dataset({
        features: ['context', 'generated_question', 'generated_answer'],
        num_rows: 706
    })
})
Loading T5 tokenizer from local path: ./models\t5_small
Applying T5 preprocessing to the dataset...

Map:   0%|          | 0/6352 [00:00<?, ? examples/s]

Map:   0%|          | 0/706 [00:00<?, ? examples/s]

Preprocessing complete.
Loading T5 model from local path: ./models\t5_small
Initializing Trainer...

C:\Users\jimma\AppData\Local\Temp\ipykernel_12324\245529600.py:82: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 *** STARTING T5 FINE-TUNING! *** 🚀

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

✅ *** T5 FINE-TUNING COMPLETE! *** ✅
Saving the best model to ./models\my_final_T5_qa_model...
Model saved successfully.